In [1]:
import pandas as pd

df = pd.read_excel('/kaggle/input/datasets/mgbleh/carbook/CarBook.xlsx')
df.head()

,Car_ID,Brand,Model,Year,Fuel_Type,Transmission,Price,Mileage,Engine_CC,Seating_Capacity,Service_Cost
0,1,Toyota,Innova,2024,CNG,Manual,2020000,27.3,800,4,24100
1,2,Kia,EV6,2023,Diesel,Manual,1770000,16.4,2500,7,18800
2,3,Maruti Suzuki,Dzire,2016,Petrol,Manual,3430000,17.6,2000,6,24700
3,4,Honda,Amaze,2019,Petrol,Manual,1610000,19.2,2500,6,23300
4,5,Honda,City,2015,Electric,Manual,1840000,15.8,1000,5,5800

In [2]:
import os

for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/datasets/mgbleh/carbook/CarBook.xlsx

In [3]:
import duckdb

duckdb.query("""
CREATE TABLE cars (
    Car_ID INTEGER,
    Brand TEXT,
    Model TEXT,
    Year INTEGER,
    Fuel_Type TEXT,
    Transmission TEXT,
    Price INTEGER,
    Mileage FLOAT,
    Engine_CC INTEGER,
    Seating_Capacity INTEGER,
    Service_Cost INTEGER
)
""")

In [4]:
import duckdb

duckdb.query("CREATE OR REPLACE TABLE cars AS SELECT * FROM df")

In [5]:
result = duckdb.query("SELECT * FROM cars LIMIT 5").to_df()
result

,Car_ID,Brand,Model,Year,Fuel_Type,Transmission,Price,Mileage,Engine_CC,Seating_Capacity,Service_Cost
0,1,Toyota,Innova,2024,CNG,Manual,2020000,27.3,800,4,24100
1,2,Kia,EV6,2023,Diesel,Manual,1770000,16.4,2500,7,18800
2,3,Maruti Suzuki,Dzire,2016,Petrol,Manual,3430000,17.6,2000,6,24700
3,4,Honda,Amaze,2019,Petrol,Manual,1610000,19.2,2500,6,23300
4,5,Honda,City,2015,Electric,Manual,1840000,15.8,1000,5,5800

In [6]:
import duckdb

query = """
SELECT Brand,
       ROUND(AVG(Price),0) AS avg_price
FROM cars
GROUP BY Brand
ORDER BY avg_price DESC
"""

result = duckdb.query(query).to_df()
result.head()

        Brand  avg_price
0    Mahindra  1996396.0
1       Honda  1972169.0
2  Volkswagen  1960909.0
3       Skoda  1955974.0
4     Renault  1950783.0

In [7]:
import duckdb

# 1️⃣ Average car price by brand
query1 = """
SELECT Brand,
       ROUND(AVG(Price),0) AS avg_price
FROM cars
GROUP BY Brand
ORDER BY avg_price DESC
"""
result1 = duckdb.query(query1).to_df()
print("1️⃣ Average car price by brand")
print(result1)


# 2️⃣ Average mileage by fuel type
query2 = """
SELECT Fuel_Type,
       ROUND(AVG(Mileage),2) AS avg_mileage
FROM cars
GROUP BY Fuel_Type
ORDER BY avg_mileage DESC
"""
result2 = duckdb.query(query2).to_df()
print("\n2️⃣ Average mileage by fuel type")
print(result2)


# 3️⃣ Most affordable car per brand (window function)
query3 = """
SELECT *
FROM (
    SELECT *,
           ROW_NUMBER() OVER(PARTITION BY Brand ORDER BY Price) AS rn
    FROM cars
)
WHERE rn = 1
"""
result3 = duckdb.query(query3).to_df()
print("\n3️⃣ Most affordable car per brand")
print(result3)


# 4️⃣ Car count by transmission type
query4 = """
SELECT Transmission,
       COUNT(*) AS num_models
FROM cars
GROUP BY Transmission
"""
result4 = duckdb.query(query4).to_df()
print("\n4️⃣ Car count by transmission type")
print(result4)


# 5️⃣ Price vs Engine Category
query5 = """
SELECT
    CASE
        WHEN Engine_CC < 1200 THEN 'Small Engine'
        WHEN Engine_CC BETWEEN 1200 AND 1800 THEN 'Medium Engine'
        ELSE 'Large Engine'
    END AS engine_category,
    ROUND(AVG(Price),0) AS avg_price
FROM cars
GROUP BY engine_category
ORDER BY avg_price
"""
result5 = duckdb.query(query5).to_df()
print("\n5️⃣ Price vs Engine Category")
print(result5)


# 6️⃣ Top 10 most economical cars (high mileage, low price)
query6 = """
SELECT Brand, Model, Price, Mileage
FROM cars
ORDER BY Mileage DESC, Price ASC
LIMIT 10
"""
result6 = duckdb.query(query6).to_df()
print("\n6️⃣ Top 10 most economical cars")
print(result6)


# 7️⃣ Annual ownership cost over 5 years
query7 = """
SELECT Brand, Model,
       Price + (Service_Cost * 5) AS five_year_cost
FROM cars
ORDER BY five_year_cost ASC
LIMIT 10
"""
result7 = duckdb.query(query7).to_df()
print("\n7️⃣ Annual ownership cost over 5 years")
print(result7)


# 8️⃣ Average service cost by brand
query8 = """
SELECT Brand,
       ROUND(AVG(Service_Cost),0) AS avg_service_cost
FROM cars
GROUP BY Brand
ORDER BY avg_service_cost DESC
"""
result8 = duckdb.query(query8).to_df()
print("\n8️⃣ Average service cost by brand")
print(result8)


# 9️⃣ Cars with seating >= 7 and high mileage
query9 = """
SELECT Brand, Model, Seating_Capacity, Mileage
FROM cars
WHERE Seating_Capacity >= 7
ORDER BY Mileage DESC
"""
result9 = duckdb.query(query9).to_df()
print("\n9️⃣ Cars with seating >= 7 and high mileage")
print(result9)


# 🔟 Recent models with premium pricing (Year >= 2022, Price > 15 lakh INR)
query10 = """
SELECT Brand, Model, Year, Price
FROM cars
WHERE Year >= 2022 AND Price > 1500000
ORDER BY Price DESC
"""
result10 = duckdb.query(query10).to_df()
print("\n🔟 Recent models with premium pricing")
print(result10)

1️⃣ Average car price by brand
           Brand  avg_price
0       Mahindra  1996396.0
1          Honda  1972169.0
2     Volkswagen  1960909.0
3          Skoda  1955974.0
4        Renault  1950783.0
5         Toyota  1939549.0
6        Hyundai  1932594.0
7  Maruti Suzuki  1917831.0
8            Kia  1917307.0
9    Tata Motors  1916198.0

2️⃣ Average mileage by fuel type
  Fuel_Type  avg_mileage
0       CNG        20.10
1    Diesel        20.00
2    Petrol        19.91
3  Electric        19.85

3️⃣ Most affordable car per brand
   Car_ID          Brand     Model  Year Fuel_Type Transmission   Price  \
0     709          Honda      Jazz  2018    Petrol       Manual  400000
1    4523    Tata Motors     Nexon  2024    Petrol    Automatic  400000
2    1286          Skoda    Slavia  2020  Electric       Manual  400000
3    8070  Maruti Suzuki     Swift  2023  Electric    Automatic  400000
4    9189            Kia    Seltos  2021  Electric    Automatic  400000
5    3389       Mahindra    XUV700  2022  Electric    Automatic  410000
6    6135        Hyundai     Creta  2020    Petrol    Automatic  400000
7    5308         Toyota  Fortuner  2019  Electric       Manual  400000
8    2423     Volkswagen    Virtus  2016       CNG       Manual  400000
9    6540        Renault     Kiger  2017    Petrol       Manual  410000

   Mileage  Engine_CC  Seating_Capacity  Service_Cost  rn
0     19.8       1000                 5         12500   1
1     23.3        800                 7         14800   1
2     17.6       1500                 7         19600   1
3     15.4       2500                 7         21400   1
4     28.0       1800                 6         19100   1
5     10.6       1200                 4         24000   1
6     25.5        800                 6         20000   1
7     23.2        800                 7         11200   1
8     23.6       2000                 4         18700   1
9     26.0       2500                 6         21000   1

4️⃣ Car count by transmission type
  Transmission  num_models
0       Manual        5045
1    Automatic        4955

5️⃣ Price vs Engine Category
  engine_category  avg_price
0    Large Engine  1917185.0
1    Small Engine  1952570.0
2   Medium Engine  1961077.0

6️⃣ Top 10 most economical cars
           Brand     Model    Price  Mileage
0          Skoda     Rapid   620000     30.0
1        Hyundai       i20   710000     30.0
2  Maruti Suzuki    Baleno   800000     30.0
3        Hyundai     Verna   990000     30.0
4        Hyundai       i20  1130000     30.0
5         Toyota    Glanza  1200000     30.0
6            Kia    Carens  1280000     30.0
7     Volkswagen      Polo  1300000     30.0
8         Toyota  Fortuner  1390000     30.0
9  Maruti Suzuki     Dzire  1520000     30.0

7️⃣ Annual ownership cost over 5 years
         Brand     Model  five_year_cost
0       Toyota  Fortuner          432500
1     Mahindra    XUV700          435000
2        Skoda    Slavia          440500
3       Toyota    Glanza          442500
4   Volkswagen      Polo          443500
5        Honda     Amaze          446000
6          Kia    Carens          446500
7  Tata Motors     Tiago          449000
8      Hyundai       i20          451000
9        Skoda    Superb          454000

8️⃣ Average service cost by brand
           Brand  avg_service_cost
0        Renault           15218.0
1  Maruti Suzuki           15094.0
2         Toyota           15066.0
3       Mahindra           15027.0
4            Kia           15008.0
5     Volkswagen           14992.0
6    Tata Motors           14983.0
7          Skoda           14957.0
8        Hyundai           14712.0
9          Honda           14645.0

9️⃣ Cars with seating >= 7 and high mileage
              Brand     Model  Seating_Capacity  Mileage
0          Mahindra    XUV300                 7     30.0
1               Kia    Seltos                 7     30.0
2     Maruti Suzuki     Dzire                 7     30.0
3        Volkswagen    Tiguan                 7     30.0
4           Hyundai       i20                 7     29.9
...             ...       ...               ...      ...
2554        Renault     Lodgy                 7     10.0
2555        Renault    Triber                 7     10.0
2556         Toyota  Fortuner                 7     10.0
2557        Renault     Lodgy                 7     10.0
2558        Renault    Duster                 7     10.0

[2559 rows x 4 columns]

🔟 Recent models with premium pricing
              Brand   Model  Year    Price
0     Maruti Suzuki  Ertiga  2023  3500000
1             Skoda   Rapid  2022  3500000
2               Kia     EV6  2023  3500000
3           Renault    Kwid  2022  3500000
4             Skoda  Superb  2024  3500000
...             ...     ...   ...      ...
1984  Maruti Suzuki   Dzire  2024  1510000
1985        Hyundai   Creta  2023  1510000
1986            Kia   Sonet  2024  1510000
1987  Maruti Suzuki  Baleno  2022  1510000
1988          Skoda  Kushaq  2023  1510000

[1989 rows x 4 columns]

In [8]:
import duckdb

# Top 10 most affordable cars based on Price + Service_Cost
query_affordable = """
SELECT Brand,
       Model,
       Price,
       Service_Cost,
       (Price + Service_Cost) AS total_cost
FROM cars
ORDER BY total_cost ASC
LIMIT 10
"""

result_affordable = duckdb.query(query_affordable).to_df()
print("Top 10 most affordable cars (Price + Service Cost)")
print(result_affordable)

Top 10 most affordable cars (Price + Service Cost)
         Brand          Model   Price  Service_Cost  total_cost
0       Toyota       Fortuner  400000          6500      406500
1       Toyota       Fortuner  400000         11200      411200
2       Toyota  Urban Cruiser  400000         11600      411600
3        Honda           Jazz  400000         12500      412500
4        Honda           Jazz  400000         13100      413100
5          Kia            EV6  400000         13300      413300
6  Tata Motors          Nexon  400000         14800      414800
7     Mahindra         XUV700  410000          5000      415000
8        Skoda         Slavia  410000          6100      416100
9          Kia       Carnival  400000         16300      416300

In [9]:
import duckdb

# 1️⃣ Top 3 most affordable cars per brand
query1 = """
SELECT *
FROM (
    SELECT *,
           ROW_NUMBER() OVER (PARTITION BY Brand ORDER BY (Price + Service_Cost) ASC) AS brand_rank
    FROM cars
)
WHERE brand_rank <= 3
ORDER BY Brand, brand_rank
"""
result1 = duckdb.query(query1).to_df()
print("1️⃣ Top 3 most affordable cars per brand")
print(result1)


# 2️⃣ Cars with mileage above brand average
query2 = """
SELECT Brand, Model, Mileage
FROM cars
WHERE Mileage > (
    SELECT AVG(Mileage) 
    FROM cars AS c2
    WHERE c2.Brand = cars.Brand
)
ORDER BY Brand, Mileage DESC
"""
result2 = duckdb.query(query2).to_df()
print("\n2️⃣ Cars with mileage above brand average")
print(result2)


# 3️⃣ Price quartiles (segmentation)
query3 = """
SELECT *,
       NTILE(4) OVER (ORDER BY Price DESC) AS price_quartile
FROM cars
ORDER BY Price DESC
"""
result3 = duckdb.query(query3).to_df()
print("\n3️⃣ Price quartiles for cars")
print(result3)


# 4️⃣ Cumulative total cost by ascending affordability
query4 = """
SELECT Brand, Model, Price, Service_Cost,
       SUM(Price + Service_Cost) OVER (ORDER BY (Price + Service_Cost)) AS cumulative_cost
FROM cars
ORDER BY cumulative_cost
"""
result4 = duckdb.query(query4).to_df()
print("\n4️⃣ Cumulative total cost by affordability")
print(result4)


# 5️⃣ Average price by fuel type and transmission
query5 = """
SELECT Fuel_Type,
       Transmission,
       ROUND(AVG(Price),0) AS avg_price
FROM cars
GROUP BY Fuel_Type, Transmission
ORDER BY Fuel_Type, Transmission
"""
result5 = duckdb.query(query5).to_df()
print("\n5️⃣ Average price by fuel type and transmission")
print(result5)


# 6️⃣ Price categories: Budget / Mid-range / Premium
query6 = """
SELECT Brand, Model, Price,
       CASE
           WHEN Price < 500000 THEN 'Budget'
           WHEN Price BETWEEN 500000 AND 1500000 THEN 'Mid-range'
           ELSE 'Premium'
       END AS price_category
FROM cars
ORDER BY Price
"""
result6 = duckdb.query(query6).to_df()
print("\n6️⃣ Price categories for cars")
print(result6)


# 7️⃣ Top 5 most economical cars by fuel type
query7 = """
SELECT *
FROM (
    SELECT *,
           ROW_NUMBER() OVER (PARTITION BY Fuel_Type ORDER BY Mileage DESC, Price ASC) AS rn
    FROM cars
)
WHERE rn <= 5
ORDER BY Fuel_Type, rn
"""
result7 = duckdb.query(query7).to_df()
print("\n7️⃣ Top 5 most economical cars by fuel type")
print(result7)


# 8️⃣ Rank cars by total cost across all brands
query8 = """
SELECT Brand, Model, Price, Service_Cost,
       (Price + Service_Cost) AS total_cost,
       RANK() OVER (ORDER BY (Price + Service_Cost) ASC) AS affordability_rank
FROM cars
ORDER BY affordability_rank
LIMIT 10
"""
result8 = duckdb.query(query8).to_df()
print("\n8️⃣ Rank cars by total cost (top 10)")
print(result8)


# 9️⃣ Average service cost by brand, ordered descending
query9 = """
SELECT Brand,
       ROUND(AVG(Service_Cost),0) AS avg_service_cost
FROM cars
GROUP BY Brand
ORDER BY avg_service_cost DESC
"""
result9 = duckdb.query(query9).to_df()
print("\n9️⃣ Average service cost by brand")
print(result9)


# 🔟 Cars with engine > 1800 CC and high price
query10 = """
SELECT Brand, Model, Engine_CC, Price
FROM cars
WHERE Engine_CC > 1800 AND Price > 1500000
ORDER BY Price DESC
"""
result10 = duckdb.query(query10).to_df()
print("\n🔟 Cars with engine > 1800 CC and high price")
print(result10)

1️⃣ Top 3 most affordable cars per brand
    Car_ID          Brand          Model  Year Fuel_Type Transmission   Price  \
0      709          Honda           Jazz  2018    Petrol       Manual  400000
1     4267          Honda           Jazz  2018    Diesel       Manual  400000
2     9563          Honda          Amaze  2022       CNG    Automatic  420000
3     6135        Hyundai          Creta  2020    Petrol    Automatic  400000
4      993        Hyundai          Venue  2017  Electric    Automatic  410000
5     6647        Hyundai            i20  2022    Petrol       Manual  420000
6     1504            Kia            EV6  2020    Petrol    Automatic  400000
7     3617            Kia       Carnival  2016    Petrol       Manual  400000
8     9942            Kia         Carens  2020       CNG    Automatic  410000
9     1202       Mahindra         XUV700  2017  Electric    Automatic  410000
10    7277       Mahindra           Thar  2021  Electric    Automatic  420000
11     475       Mahindra         XUV700  2018  Electric       Manual  410000
12    8530  Maruti Suzuki         Baleno  2019    Diesel       Manual  400000
13    8070  Maruti Suzuki          Swift  2023  Electric    Automatic  400000
14    9132  Maruti Suzuki         Ertiga  2019  Electric       Manual  410000
15    8979        Renault         Triber  2020  Electric    Automatic  410000
16    6599        Renault          Lodgy  2019    Diesel       Manual  410000
17    1510        Renault          Kiger  2019       CNG       Manual  420000
18    1509          Skoda         Slavia  2020    Petrol       Manual  410000
19    5392          Skoda         Superb  2023  Electric       Manual  410000
20    1286          Skoda         Slavia  2020  Electric       Manual  400000
21    4523    Tata Motors          Nexon  2024    Petrol    Automatic  400000
22    4185    Tata Motors          Tiago  2018       CNG    Automatic  410000
23    3210    Tata Motors          Nexon  2023  Electric    Automatic  400000
24    9669         Toyota       Fortuner  2021    Petrol       Manual  400000
25    5308         Toyota       Fortuner  2019  Electric       Manual  400000
26    6128         Toyota  Urban Cruiser  2023    Diesel       Manual  400000
27    8275     Volkswagen           Polo  2022    Petrol    Automatic  410000
28    2423     Volkswagen         Virtus  2016       CNG       Manual  400000
29    9899     Volkswagen          Vento  2020       CNG    Automatic  410000

    Mileage  Engine_CC  Seating_Capacity  Service_Cost  brand_rank
0      19.8       1000                 5         12500           1
1      17.3       1500                 6         13100           2
2      12.2       1200                 4          5200           3
3      25.5        800                 6         20000           1
4      24.3       1200                 7         13700           2
5      25.3       2500                 7          6200           3
6      26.4       2500                 4         13300           1
7      22.4       1200                 6         16300           2
8      17.6        800                 7          7300           3
9      10.6       2000                 6          5000           1
10     26.8       1000                 5          8300           2
11     12.7       2000                 5         20100           3
12     29.6        800                 7         19100           1
13     15.4       2500                 7         21400           2
14     14.8       2500                 6         21100           3
15     22.4        800                 4         11100           1
16     13.9       1200                 6         13700           2
17     16.2       1500                 6          7600           3
18     24.3       2000                 7          6100           1
19     28.8       1000                 4          8800           2
20     17.6       1500                 7         19600           3
21     23.3        800                 7         14800           1
22     24.2        800                 7          7800           2
23     21.1       2000                 5         19900           3
24     14.3       1500                 5          6500           1
25     23.2        800                 7         11200           2
26     21.7       2000                 4         11600           3
27     14.5        800                 6          6700           1
28     23.6       2000                 4         18700           2
29     25.4        800                 6          9800           3

2️⃣ Cars with mileage above brand average
           Brand   Model  Mileage
0          Honda   Civic     29.9
1          Honda   Amaze     29.9
2          Honda    City     29.9
3          Honda    Jazz     29.9
4          Honda    City     29.9
...          ...     ...      ...
4996  Volkswagen    Polo     20.0
4997  Volkswagen   Vento     20.0
4998  Volkswagen  Tiguan     19.9
4999  Volkswagen  Taigun     19.9
5000  Volkswagen   Vento     19.9

[5001 rows x 3 columns]

3️⃣ Price quartiles for cars
      Car_ID          Brand     Model  Year Fuel_Type Transmission    Price  \
0        901  Maruti Suzuki    Ertiga  2023  Electric    Automatic  3500000
1       1153        Hyundai     Venue  2015       CNG       Manual  3500000
2       2594        Renault     Lodgy  2020       CNG    Automatic  3500000
3       3157          Skoda     Rapid  2022       CNG    Automatic  3500000
4       3755            Kia       EV6  2023  Electric       Manual  3500000
...      ...            ...       ...   ...       ...          ...      ...
9995    8070  Maruti Suzuki     Swift  2023  Electric    Automatic   400000
9996    8530  Maruti Suzuki    Baleno  2019    Diesel       Manual   400000
9997    9189            Kia    Seltos  2021  Electric    Automatic   400000
9998    9460         Toyota    Glanza  2023    Diesel    Automatic   400000
9999    9669         Toyota  Fortuner  2021    Petrol       Manual   400000

      Mileage  Engine_CC  Seating_Capacity  Service_Cost  price_quartile
0        13.0       1200                 5         11500               1
1        14.3       1200                 5         13800               1
2        27.2       1500                 6          8600               1
3        13.9       1500                 4         19500               1
4        25.4       1800                 4          7000               1
...       ...        ...               ...           ...             ...
9995     15.4       2500                 7         21400               4
9996     29.6        800                 7         19100               4
9997     28.0       1800                 6         19100               4
9998     29.0       1000                 5         23400               4
9999     14.3       1500                 5          6500               4

[10000 rows x 12 columns]

4️⃣ Cumulative total cost by affordability
           Brand          Model    Price  Service_Cost  cumulative_cost
0         Toyota       Fortuner   400000          6500     4.065000e+05
1         Toyota       Fortuner   400000         11200     8.177000e+05
2         Toyota  Urban Cruiser   400000         11600     1.229300e+06
3          Honda           Jazz   400000         12500     1.641800e+06
4          Honda           Jazz   400000         13100     2.054900e+06
...          ...            ...      ...           ...              ...
9995       Skoda         Kushaq  3500000         21100     1.959976e+10
9996     Renault          Kiger  3500000         21100     1.959976e+10
9997       Skoda         Superb  3500000         21900     1.960328e+10
9998      Toyota       Fortuner  3500000         23200     1.960681e+10
9999  Volkswagen         Taigun  3500000         23900     1.961033e+10

[10000 rows x 5 columns]

5️⃣ Average price by fuel type and transmission
  Fuel_Type Transmission  avg_price
0       CNG    Automatic  1927019.0
1       CNG       Manual  1942030.0
2    Diesel    Automatic  1963705.0
3    Diesel       Manual  1926389.0
4  Electric    Automatic  1932641.0
5  Electric       Manual  1971297.0
6    Petrol    Automatic  1925547.0
7    Petrol       Manual  1977795.0

6️⃣ Price categories for cars
              Brand     Model    Price price_category
0             Honda      Jazz   400000         Budget
1             Skoda    Slavia   400000         Budget
2               Kia       EV6   400000         Budget
3        Volkswagen    Virtus   400000         Budget
4       Tata Motors     Punch   400000         Budget
...             ...       ...      ...            ...
9995     Volkswagen    Virtus  3500000        Premium
9996         Toyota  Fortuner  3500000        Premium
9997        Renault     Kiger  3500000        Premium
9998     Volkswagen    Virtus  3500000        Premium
9999  Maruti Suzuki     Swift  3500000        Premium

[10000 rows x 4 columns]

7️⃣ Top 5 most economical cars by fuel type
    Car_ID          Brand     Model  Year Fuel_Type Transmission    Price  \
0     2622            Kia    Carens  2020       CNG       Manual  1280000
1     4029            Kia     Sonet  2024       CNG    Automatic  1520000
2     2904     Volkswagen    Virtus  2017       CNG       Manual  1560000
3     6797  Maruti Suzuki    Baleno  2024       CNG       Manual  1720000
4     7913  Maruti Suzuki    Ertiga  2022       CNG       Manual  1870000
5     4086     Volkswagen      Polo  2016    Diesel       Manual  1300000
6     6032  Maruti Suzuki     Dzire  2019    Diesel    Automatic  1520000
7     5002         Toyota    Glanza  2024    Diesel       Manual  3180000
8     6370     Volkswagen      Polo  2018    Diesel    Automatic   570000
9     5395    Tata Motors     Nexon  2017    Diesel       Manual  1000000
10     842          Skoda     Rapid  2017  Electric    Automatic   620000
11    3784        Hyundai       i20  2016  Electric       Manual   710000
12    1167        Hyundai     Verna  2023  Electric       Manual   990000
13    4199         Toyota  Fortuner  2016  Electric       Manual  1390000
14    7318  Maruti Suzuki     Dzire  2019  Electric       Manual  1630000
15    8580  Maruti Suzuki    Baleno  2022    Petrol       Manual   800000
16    7766        Hyundai       i20  2021    Petrol       Manual  1130000
17    7535         Toyota    Glanza  2017    Petrol       Manual  1200000
18    8658        Hyundai       i20  2021    Petrol       Manual  1730000
19    4088  Maruti Suzuki    WagonR  2021    Petrol    Automatic  2130000

    Mileage  Engine_CC  Seating_Capacity  Service_Cost  rn
0      30.0       1500                 5          7800   1
1      30.0       2500                 4          8200   2
2      30.0       1000                 5         11700   3
3      30.0       1200                 6          5200   4
4      30.0       1500                 4         22000   5
5      30.0       2000                 6         14300   1
6      30.0       1200                 7         13800   2
7      30.0       1000                 5          8600   3
8      29.9       2500                 5         20600   4
9      29.9       2000                 5         10900   5
10     30.0       1800                 6         16200   1
11     30.0       1200                 4         11800   2
12     30.0       1000                 4         16100   3
13     30.0       1500                 4          7100   4
14     30.0       1500                 4         14900   5
15     30.0        800                 6         16800   1
16     30.0       1000                 5          6500   2
17     30.0        800                 5         24200   3
18     30.0       2000                 4         17400   4
19     30.0        800                 6         13800   5

8️⃣ Rank cars by total cost (top 10)
         Brand          Model   Price  Service_Cost  total_cost  \
0       Toyota       Fortuner  400000          6500      406500
1       Toyota       Fortuner  400000         11200      411200
2       Toyota  Urban Cruiser  400000         11600      411600
3        Honda           Jazz  400000         12500      412500
4        Honda           Jazz  400000         13100      413100
5          Kia            EV6  400000         13300      413300
6  Tata Motors          Nexon  400000         14800      414800
7     Mahindra         XUV700  410000          5000      415000
8        Skoda         Slavia  410000          6100      416100
9          Kia       Carnival  400000         16300      416300

   affordability_rank
0                   1
1                   2
2                   3
3                   4
4                   5
5                   6
6                   7
7                   8
8                   9
9                  10

9️⃣ Average service cost by brand
           Brand  avg_service_cost
0        Renault           15218.0
1  Maruti Suzuki           15094.0
2         Toyota           15066.0
3       Mahindra           15027.0
4            Kia           15008.0
5     Volkswagen           14992.0
6    Tata Motors           14983.0
7          Skoda           14957.0
8        Hyundai           14712.0
9          Honda           14645.0

🔟 Cars with engine > 1800 CC and high price
              Brand   Model  Engine_CC    Price
0             Skoda  Kushaq       2000  3500000
1             Skoda  Superb       2500  3500000
2        Volkswagen  Taigun       2000  3500000
3     Maruti Suzuki   Dzire       2000  3490000
4           Renault   Kiger       2000  3490000
...             ...     ...        ...      ...
1824          Skoda  Superb       2500  1510000
1825        Hyundai   Creta       2000  1510000
1826       Mahindra    Thar       2500  1510000
1827            Kia   Sonet       2500  1510000
1828         Toyota  Innova       2000  1510000

[1829 rows x 4 columns]